site_name: Kotlin for FRC
site_url: https://kotlin-for-frc.github.io/

extra_css:
  - stylesheets/extra.css


  
nav:
  - Home: index.md
  - Getting Started:
    - Installing Tools: getting-started/installation.md
    - Why Kotlin: getting-started/why-kotlin.md
    - Running your robot program: getting-started/running.md
  - Developing with Kotlin:
    - Migrating from Java: developing/migrating.md

theme:
  name: material
  palette:
    scheme: slate
    primary: custom
    accent: custom
  logo: img/k4frc.png
  favicon: img/k4frc.png
